export const userAuthType = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',
};

export const jobsType = {
    JOBS_REQUEST: 'JOBS_REQUEST',
    JOBS_SUCCESS: 'JOBS_SUCCESS',
    JOBS_FAILURE: 'JOBS_FAILURE',

}

export const favoriteJobsType = {
    JOBS_FAVORITE_SUCCESS: 'JOBS_FAVORITE_SUCCESS',
    JOBS_FAVORITE_FAILURE: 'JOBS_FAVORITE_FAILURE',

}

export const userType = {
    USER_REQUEST: 'USER_REQUEST',
    USER_SUCCESS: 'USER_SUCCESS',
    USER_FAILURE: 'USER_FAILURE',

}